/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type ActivitiesTeachingContentPageActivityTransformer from '#src/activities/transformers/teaching_content_page_activity_transformer'
import type ChaptersTeachingContentPageChapterTransformer from '#src/chapters/transformers/teaching_content_page_chapter_transformer'
import type TeachingContentTeachingContentPageActivityTypeTransformer from '#src/teaching_content/transformers/teaching_content_page_activity_type_transformer'
import type TeachingContentTeachingContentPageLevelTransformer from '#src/teaching_content/transformers/teaching_content_page_level_transformer'
import type TeachingContentTeachingContentPageSchoolYearTransformer from '#src/teaching_content/transformers/teaching_content_page_school_year_transformer'
import type TeachingContentTeachingContentPageTransformer from '#src/teaching_content/transformers/teaching_content_page_transformer'
import type ThemesTeachingContentPageThemeTransformer from '#src/themes/transformers/teaching_content_page_theme_transformer'
import type ThemesThemeTransformer from '#src/themes/transformers/theme_transformer'
import type UserTransformer from '#src/transformers/user_transformer'
import type InertiaMiddleware from '#middlewares/inertia_middleware'

export namespace Data {
  export namespace Activities {
    export type TeachingContentPageActivity = InferData<ActivitiesTeachingContentPageActivityTransformer>
    export namespace TeachingContentPageActivity {
      export type Variants = InferVariants<ActivitiesTeachingContentPageActivityTransformer>
    }
  }
  export namespace Chapters {
    export type TeachingContentPageChapter = InferData<ChaptersTeachingContentPageChapterTransformer>
    export namespace TeachingContentPageChapter {
      export type Variants = InferVariants<ChaptersTeachingContentPageChapterTransformer>
    }
  }
  export namespace TeachingContent {
    export type TeachingContentPageActivityType = InferData<TeachingContentTeachingContentPageActivityTypeTransformer>
    export namespace TeachingContentPageActivityType {
      export type Variants = InferVariants<TeachingContentTeachingContentPageActivityTypeTransformer>
    }
    export type TeachingContentPageLevel = InferData<TeachingContentTeachingContentPageLevelTransformer>
    export namespace TeachingContentPageLevel {
      export type Variants = InferVariants<TeachingContentTeachingContentPageLevelTransformer>
    }
    export type TeachingContentPageSchoolYear = InferData<TeachingContentTeachingContentPageSchoolYearTransformer>
    export namespace TeachingContentPageSchoolYear {
      export type Variants = InferVariants<TeachingContentTeachingContentPageSchoolYearTransformer>
    }
    export type TeachingContentPage = InferData<TeachingContentTeachingContentPageTransformer>
    export namespace TeachingContentPage {
      export type Variants = InferVariants<TeachingContentTeachingContentPageTransformer>
    }
  }
  export namespace Themes {
    export type TeachingContentPageTheme = InferData<ThemesTeachingContentPageThemeTransformer>
    export namespace TeachingContentPageTheme {
      export type Variants = InferVariants<ThemesTeachingContentPageThemeTransformer>
    }
    export type Theme = InferData<ThemesThemeTransformer>
    export namespace Theme {
      export type Variants = InferVariants<ThemesThemeTransformer>
    }
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
