/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type UserTransformer from '#src/transformers/user_transformer'
import type TeachingContentTeachingContentPageTransformer from '#src/teaching_content/transformers/teaching_content_page_transformer'
import type TeachingContentThemeTransformer from '#src/teaching_content/transformers/theme_transformer'
import type InertiaMiddleware from '#middlewares/inertia_middleware'

export namespace Data {
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export namespace TeachingContent {
    export type TeachingContentPage = InferData<TeachingContentTeachingContentPageTransformer>
    export namespace TeachingContentPage {
      export type Variants = InferVariants<TeachingContentTeachingContentPageTransformer>
    }
    export type Theme = InferData<TeachingContentThemeTransformer>
    export namespace Theme {
      export type Variants = InferVariants<TeachingContentThemeTransformer>
    }
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
