/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type TeachingContentTeachingContentPageActivityTransformer from '#src/teaching_content/transformers/teaching_content_page_activity_transformer'
import type TeachingContentTeachingContentPageActivityTypeTransformer from '#src/teaching_content/transformers/teaching_content_page_activity_type_transformer'
import type TeachingContentTeachingContentPageChapterTransformer from '#src/teaching_content/transformers/teaching_content_page_chapter_transformer'
import type TeachingContentTeachingContentPageLevelTransformer from '#src/teaching_content/transformers/teaching_content_page_level_transformer'
import type TeachingContentTeachingContentPageSchoolYearTransformer from '#src/teaching_content/transformers/teaching_content_page_school_year_transformer'
import type TeachingContentTeachingContentPageThemeTransformer from '#src/teaching_content/transformers/teaching_content_page_theme_transformer'
import type TeachingContentTeachingContentPageTransformer from '#src/teaching_content/transformers/teaching_content_page_transformer'
import type TeachingContentThemeTransformer from '#src/teaching_content/transformers/theme_transformer'
import type UserTransformer from '#src/transformers/user_transformer'
import type InertiaMiddleware from '#middlewares/inertia_middleware'

export namespace Data {
  export namespace TeachingContent {
    export type TeachingContentPageActivity = InferData<TeachingContentTeachingContentPageActivityTransformer>
    export namespace TeachingContentPageActivity {
      export type Variants = InferVariants<TeachingContentTeachingContentPageActivityTransformer>
    }
    export type TeachingContentPageActivityType = InferData<TeachingContentTeachingContentPageActivityTypeTransformer>
    export namespace TeachingContentPageActivityType {
      export type Variants = InferVariants<TeachingContentTeachingContentPageActivityTypeTransformer>
    }
    export type TeachingContentPageChapter = InferData<TeachingContentTeachingContentPageChapterTransformer>
    export namespace TeachingContentPageChapter {
      export type Variants = InferVariants<TeachingContentTeachingContentPageChapterTransformer>
    }
    export type TeachingContentPageLevel = InferData<TeachingContentTeachingContentPageLevelTransformer>
    export namespace TeachingContentPageLevel {
      export type Variants = InferVariants<TeachingContentTeachingContentPageLevelTransformer>
    }
    export type TeachingContentPageSchoolYear = InferData<TeachingContentTeachingContentPageSchoolYearTransformer>
    export namespace TeachingContentPageSchoolYear {
      export type Variants = InferVariants<TeachingContentTeachingContentPageSchoolYearTransformer>
    }
    export type TeachingContentPageTheme = InferData<TeachingContentTeachingContentPageThemeTransformer>
    export namespace TeachingContentPageTheme {
      export type Variants = InferVariants<TeachingContentTeachingContentPageThemeTransformer>
    }
    export type TeachingContentPage = InferData<TeachingContentTeachingContentPageTransformer>
    export namespace TeachingContentPage {
      export type Variants = InferVariants<TeachingContentTeachingContentPageTransformer>
    }
    export type Theme = InferData<TeachingContentThemeTransformer>
    export namespace Theme {
      export type Variants = InferVariants<TeachingContentThemeTransformer>
    }
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
