/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  NewAccount: () => import('#src/controllers/new_account_controller'),
  Session: () => import('#src/controllers/session_controller'),
  TeachingContentCreateChapter: () => import('#src/controllers/teaching_content_create_chapter_controller'),
  TeachingContentCreateTheme: () => import('#src/controllers/teaching_content_create_theme_controller'),
  TeachingContentThemesPage: () => import('#src/controllers/teaching_content_themes_page_controller'),
  TeachingContentUpdateChapter: () => import('#src/controllers/teaching_content_update_chapter_controller'),
  TeachingContentUpdateTheme: () => import('#src/controllers/teaching_content_update_theme_controller'),
  teachingContent: {
    TeachingContent: () => import('#src/teaching_content/controllers/teaching_content_controller'),
  },
}
