/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  activities: {
    ArchiveActivity: () => import('#src/activities/controllers/archive_activity_controller'),
    CreateActivity: () => import('#src/activities/controllers/create_activity_controller'),
    RestoreActivity: () => import('#src/activities/controllers/restore_activity_controller'),
    UpdateActivity: () => import('#src/activities/controllers/update_activity_controller'),
  },
  chapters: {
    ArchiveChapter: () => import('#src/chapters/controllers/archive_chapter_controller'),
    CreateChapter: () => import('#src/chapters/controllers/create_chapter_controller'),
    ListArchivedChapters: () => import('#src/chapters/controllers/list_archived_chapters_controller'),
    ListChapters: () => import('#src/chapters/controllers/list_chapters_controller'),
    RenderChapterEditor: () => import('#src/chapters/controllers/render_chapter_editor_controller'),
    ReorderChapters: () => import('#src/chapters/controllers/reorder_chapters_controller'),
    RestoreChapter: () => import('#src/chapters/controllers/restore_chapter_controller'),
    SelectChaptersLevel: () => import('#src/chapters/controllers/select_chapters_level_controller'),
    UpdateChapter: () => import('#src/chapters/controllers/update_chapter_controller'),
  },
  dashboard: {
    ListProgressions: () => import('#src/dashboard/controllers/list_progressions_controller'),
    ShowAnnualDashboard: () => import('#src/dashboard/controllers/show_annual_dashboard_controller'),
    ShowLevelProgressSummary: () => import('#src/dashboard/controllers/show_level_progress_summary_controller'),
    ShowProgressionView: () => import('#src/dashboard/controllers/show_progression_view_controller'),
    ShowSessionEditor: () => import('#src/dashboard/controllers/show_session_editor_controller'),
    UpdateSession: () => import('#src/dashboard/controllers/update_session_controller'),
  },
  organisation: {
    CreateClass: () => import('#src/organisation/controllers/create_class_controller'),
    CreateLevel: () => import('#src/organisation/controllers/create_level_controller'),
    ListClasses: () => import('#src/organisation/controllers/list_classes_controller'),
    ListLevels: () => import('#src/organisation/controllers/list_levels_controller'),
    ShowClassEditor: () => import('#src/organisation/controllers/show_class_editor_controller'),
    ShowLevelEditor: () => import('#src/organisation/controllers/show_level_editor_controller'),
    UpdateClass: () => import('#src/organisation/controllers/update_class_controller'),
    UpdateLevel: () => import('#src/organisation/controllers/update_level_controller'),
  },
  teachingContent: {
    DeleteActivity: () => import('#src/teaching_content/controllers/delete_activity_controller'),
    DeleteChapter: () => import('#src/teaching_content/controllers/delete_chapter_controller'),
    DeleteTheme: () => import('#src/teaching_content/controllers/delete_theme_controller'),
    TeachingContent: () => import('#src/teaching_content/controllers/teaching_content_controller'),
  },
  themes: {
    ArchiveTheme: () => import('#src/themes/controllers/archive_theme_controller'),
    CreateTheme: () => import('#src/themes/controllers/create_theme_controller'),
    ListArchivedThemes: () => import('#src/themes/controllers/list_archived_themes_controller'),
    ListThemes: () => import('#src/themes/controllers/list_themes_controller'),
    RenderThemeEditor: () => import('#src/themes/controllers/render_theme_editor_controller'),
    ReorderThemes: () => import('#src/themes/controllers/reorder_themes_controller'),
    RestoreTheme: () => import('#src/themes/controllers/restore_theme_controller'),
    SelectThemesLevel: () => import('#src/themes/controllers/select_themes_level_controller'),
    UpdateTheme: () => import('#src/themes/controllers/update_theme_controller'),
  },
}
